pipeline:
  only-on-prod:
    image: alpine:3.6
    commands:
      - echo should only be run on the prod cluster
    when:
      matrix:
        CLUSTER: prod

  build:
    image: alpine:3.6
    commands:
      - echo ${CLUSTER}

matrix:
  CLUSTER:
    - admin
    - stage
    - prod
